### ISSUE TITLE
Coveralls integration not sending coverage reports

### ISSUE THREAD

**Issue by cosmin-marginean** [cosmin-marginean/alkemy#6]
One for you @daniel-shuy: it seems that after the multi-module setup, the Coveralls data is not sent anymore.
I tried the 
```
./gradlew clean fullBuild
```
with the correct token (see `release.sh` for reference), but this doesn't seem to update: https://coveralls.io/github/cosmin-marginean/alkemy

I've tried removing the token env var `COVERALLS_REPO_TOKEN` altogether and it doesn't fail either, which is surprising (it used to fail before when this wasn't set).

I _think_ you might be able to create a Coveralls for your forked project to test this.

**Comment by daniel-shuy** [comment]
Unfortunately this is a very complicated issue.

Turns out the [multi-project example given by `coveralls-jacoco`](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin#user-content-multi-project-support---pure-kotlinjava) doesn't work, the [jacoco-report-aggregation](https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html) plugin has to be configured in the root project (see nbaztec/coveralls-jacoco-gradle-plugin#61).

After moving the JaCoCo report aggregation configuration to the root project, it still didn't work, but for a different issue that I wasn't able to solve (nbaztec/coveralls-jacoco-gradle-plugin#59). Unfortunately, this heavily involves the Gradle internal APIs and Kotlin Gradle plugin, which I am unable to find enough documentation on to solve. Also, the plugin has not been updated since Oct 2022, so I'm not hopeful for a reply from the maintainer.

I will try and see if I can get it to work with https://plugins.gradle.org/plugin/com.github.kt3k.coveralls.

**Comment by cosmin-marginean** [comment]
Yes, this something that I've looked into before and I haven't found a time a reasonable solution. 
Don't worry too much if it get hairy. Worst case you can fallback to wiring the coverage for the core library alone and we can revisit this later.
